Re-add code to allow taking over bash's diversion (Closes: #82554)
When the user doesn't want dash to be used as /bin/sh, a diversion is
added on behalf of bash.

diff --git a/debian/dash.postinst b/debian/dash.postinst
--- a/debian/dash.postinst
+++ b/debian/dash.postinst
@@ -11,11 +11,27 @@ check_divert() {
 	true)
 		if [ "$diverter" != dash ]; then
 			# Let dpkg-divert error out; we are not taking
-			# over the diversion.
-			dpkg-divert --package dash --remove $dfile
-			# Make sure we die:
-			echo "This should never be reached"
-			exit 1
+			# over the diversion, unless we added it
+			# ourselves on behalf of bash.
+			if [ "$diverter" = bash ]; then
+				dpkg-divert --package bash --remove $dfile
+			else
+				dpkg-divert --package dash --remove $dfile
+				# Make sure we die:
+				echo "This should never be reached"
+				exit 1
+			fi
+
+			dpkg-divert --package dash --divert $distrib --add $dfile
+			# remove the old equivalent of $distrib, if it existed:
+			# or $dfile if there was no previous diversion! -- should never happen, unless preinst failed
+			if [ -n "$truename" ]; then
+			       rm -f "$truename"
+			fi
+			# Safely create a slink to $ltarget at $dfile
+			# by first making a copy of $dfile at $distrib
+			cp -dp $dfile $distrib
+			ln -sf $ltarget $dfile
 		fi
 		;;
 	false)
